/*
 * Harbour 3.2.0dev (Rev. 18754)
 * LLVM/GNU C 4.2.1 (64-bit)
 * Generated C source from "src/hb/ppfuncs.prg"
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"


HB_FUNC( PPFUNCS );
HB_FUNC( __QTH_MAINWINDOW );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( QTHMAINWINDOW );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_PPFUNCS )
{ "PPFUNCS", {HB_FS_PUBLIC | HB_FS_FIRST | HB_FS_LOCAL}, {HB_FUNCNAME( PPFUNCS )}, NULL },
{ "__QTH_MAINWINDOW", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __QTH_MAINWINDOW )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "NEW", {HB_FS_PUBLIC | HB_FS_MESSAGE}, {NULL}, NULL },
{ "QTHMAINWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( QTHMAINWINDOW )}, NULL },
{ "ISDERIVEDFROM", {HB_FS_PUBLIC | HB_FS_MESSAGE}, {NULL}, NULL },
{ "ISNOTDERIVEDFROM_QTHMAINWINDOW", {HB_FS_PUBLIC | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SETWINDOWTITLE", {HB_FS_PUBLIC | HB_FS_MESSAGE}, {NULL}, NULL },
{ "MOVE", {HB_FS_PUBLIC | HB_FS_MESSAGE}, {NULL}, NULL },
{ "RESIZE", {HB_FS_PUBLIC | HB_FS_MESSAGE}, {NULL}, NULL },
{ "_CODEBLOCK_CLOSEEVENT", {HB_FS_PUBLIC | HB_FS_MESSAGE}, {NULL}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_PPFUNCS, "src/hb/ppfuncs.prg", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_PPFUNCS
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_PPFUNCS )
   #include "hbiniseg.h"
#endif

HB_FUNC( PPFUNCS )
{
   static const HB_BYTE pcode[] =
   {
	HB_P_ENDPROC
/* 00001 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( __QTH_MAINWINDOW )
{
   static const HB_BYTE pcode[] =
   {
	HB_P_FRAME, 1, 9,	/* locals, params */
/* 00003 */ HB_P_LINE, 14, 0,	/* 14 */
	HB_P_PUSHFUNCSYM, 2, 0,	/* EMPTY */
	HB_P_PUSHLOCALNEAR, 1,	/* FROMCLASS */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 23,	/* 23 (abs: 00036) */
/* 00015 */ HB_P_LINE, 16, 0,	/* 16 */
	HB_P_MESSAGE, 3, 0,	/* NEW */
	HB_P_PUSHFUNCSYM, 4, 0,	/* QTHMAINWINDOW */
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* PARENT */
	HB_P_PUSHLOCALNEAR, 3,	/* FLAGS */
	HB_P_SENDSHORT, 2,
	HB_P_POPLOCALNEAR, 10,	/* OWND */
	HB_P_JUMPNEAR, 65,	/* 65 (abs: 00099) */
/* 00036 */ HB_P_LINE, 20, 0,	/* 20 */
	HB_P_MESSAGE, 3, 0,	/* NEW */
	HB_P_PUSHLOCALNEAR, 1,	/* FROMCLASS */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'(', ')', 0, 
	HB_P_PLUS,
	HB_P_MACROPUSH, 11,
	HB_P_PUSHLOCALNEAR, 2,	/* PARENT */
	HB_P_PUSHLOCALNEAR, 3,	/* FLAGS */
	HB_P_SENDSHORT, 2,
	HB_P_POPLOCALNEAR, 10,	/* OWND */
/* 00060 */ HB_P_LINE, 22, 0,	/* 22 */
	HB_P_MESSAGE, 5, 0,	/* ISDERIVEDFROM */
	HB_P_PUSHLOCALNEAR, 10,	/* OWND */
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'Q', 'T', 'H', 'M', 'a', 'i', 'n', 'W', 'i', 'n', 'd', 'o', 'w', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_JUMPTRUENEAR, 13,	/* 13 (abs: 00099) */
/* 00088 */ HB_P_LINE, 23, 0,	/* 23 */
	HB_P_MESSAGE, 6, 0,	/* ISNOTDERIVEDFROM_QTHMAINWINDOW */
	HB_P_PUSHLOCALNEAR, 10,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00099 */ HB_P_LINE, 28, 0,	/* 28 */
	HB_P_PUSHLOCALNEAR, 4,	/* CTITLE */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00121) */
/* 00108 */ HB_P_LINE, 29, 0,	/* 29 */
	HB_P_MESSAGE, 7, 0,	/* SETWINDOWTITLE */
	HB_P_PUSHLOCALNEAR, 10,	/* OWND */
	HB_P_PUSHLOCALNEAR, 4,	/* CTITLE */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00121 */ HB_P_LINE, 32, 0,	/* 32 */
	HB_P_PUSHLOCALNEAR, 5,	/* POSX */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 23,	/* 23 (abs: 00151) */
	HB_P_PUSHLOCALNEAR, 6,	/* POSY */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00151) */
/* 00136 */ HB_P_LINE, 33, 0,	/* 33 */
	HB_P_MESSAGE, 8, 0,	/* MOVE */
	HB_P_PUSHLOCALNEAR, 10,	/* OWND */
	HB_P_PUSHLOCALNEAR, 5,	/* POSX */
	HB_P_PUSHLOCALNEAR, 6,	/* POSY */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00151 */ HB_P_LINE, 36, 0,	/* 36 */
	HB_P_PUSHLOCALNEAR, 7,	/* WIDTH */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 23,	/* 23 (abs: 00181) */
	HB_P_PUSHLOCALNEAR, 8,	/* HEIGHT */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00181) */
/* 00166 */ HB_P_LINE, 37, 0,	/* 37 */
	HB_P_MESSAGE, 9, 0,	/* RESIZE */
	HB_P_PUSHLOCALNEAR, 10,	/* OWND */
	HB_P_PUSHLOCALNEAR, 7,	/* WIDTH */
	HB_P_PUSHLOCALNEAR, 8,	/* HEIGHT */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00181 */ HB_P_LINE, 40, 0,	/* 40 */
	HB_P_PUSHLOCALNEAR, 9,	/* CODEBLOCK_CLOSEEVENT */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00203) */
/* 00190 */ HB_P_LINE, 41, 0,	/* 41 */
	HB_P_MESSAGE, 10, 0,	/* _CODEBLOCK_CLOSEEVENT */
	HB_P_PUSHLOCALNEAR, 10,	/* OWND */
	HB_P_PUSHLOCALNEAR, 9,	/* CODEBLOCK_CLOSEEVENT */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00203 */ HB_P_LINE, 46, 0,	/* 46 */
	HB_P_PUSHLOCALNEAR, 10,	/* OWND */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00210 */
   };

   hb_vmExecute( pcode, symbols );
}

